# Generated by Django 5.2.13 on 2026-04-29 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_add_matriculados_to_asignatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Limitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del problema')),
                ('tipo', models.CharField(choices=[('AUSENCIA', 'Ausencia'), ('RETRASO', 'Retraso'), ('CAMBIO_AULA', 'Cambio de aula'), ('MATERIAL', 'Falta de material'), ('OTRO', 'Otro')], default='AUSENCIA', max_length=15, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripción del problema')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADA', 'Revisada'), ('RESUELTA', 'Resuelta'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('respuesta_decano', models.TextField(blank=True, verbose_name='Respuesta del decano')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.asignatura', verbose_name='Asignatura afectada')),
                ('bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.bloquehorario', verbose_name='Bloque horario')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limitaciones_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Limitación',
                'verbose_name_plural': 'Limitaciones',
                'ordering': ['-creada_en'],
            },
        ),
    ]
