[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate --noinput && python manage.py seed_datos && python manage.py seed_profesores && gunicorn config.wsgi --bind 0.0.0.0:$PORT --workers 2 --log-file -"
