# Generated by Django 5.2.13 on 2026-04-11 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del bloque')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('turno', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], max_length=6, verbose_name='Turno')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bloque Horario',
                'verbose_name_plural': 'Bloques Horarios',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número de curso')),
                ('es_ultimo', models.BooleanField(default=False, help_text='Las clases de este curso se generan exclusivamente por la tarde (RD-04)', verbose_name='¿Es último curso?')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['titulacion', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Titulación',
                'verbose_name_plural': 'Titulaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('horas_sesion', models.PositiveSmallIntegerField(default=2, verbose_name='Horas por sesión')),
                ('sesiones_semana', models.PositiveSmallIntegerField(default=2, verbose_name='Sesiones por semana')),
                ('es_compartida', models.BooleanField(default=False, help_text='RD-10: obliga a bloquear el mismo slot en todas las titulaciones vinculadas', verbose_name='¿Compartida entre titulaciones?')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='academic.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['curso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')], verbose_name='Día')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('tipo', models.CharField(choices=[('PREFERENTE', 'Disponibilidad preferente'), ('BLOQUEADO', 'Bloqueo (no disponible)')], default='PREFERENTE', max_length=15, verbose_name='Tipo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='academic.profesor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Disponibilidad del Profesor',
                'verbose_name_plural': 'Disponibilidades de Profesores',
            },
        ),
        migrations.CreateModel(
            name='AsignacionProfesorAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='academic.asignatura', verbose_name='Asignatura')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academic.profesor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Asignación Profesor–Asignatura',
                'verbose_name_plural': 'Asignaciones Profesor–Asignatura',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='academic.titulacion', verbose_name='Titulación'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('titulacion', 'numero')},
        ),
        migrations.CreateModel(
            name='AsignaturaCompartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidas', to='academic.asignatura', verbose_name='Asignatura')),
                ('titulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_compartidas', to='academic.titulacion', verbose_name='Titulación')),
            ],
            options={
                'verbose_name': 'Asignatura Compartida',
                'verbose_name_plural': 'Asignaturas Compartidas',
                'unique_together': {('asignatura', 'titulacion')},
            },
        ),
    ]
