# Generated by Django 5.2.13 on 2026-04-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='semestre',
            field=models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], default=1, verbose_name='Semestre'),
        ),
    ]
