# Generated by Django 5.2.13 on 2026-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_add_semestre_to_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='matriculados',
            field=models.PositiveIntegerField(default=0, help_text='Foro de grado: si es inferior al umbral configurado, la asignatura se trata como exclusiva aunque esté marcada como compartida', verbose_name='Alumnos matriculados'),
        ),
    ]
