# Generated by Django 5.2.13 on 2026-04-29 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_add_semestre_to_asignatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')])),
                ('anio_academico', models.CharField(default='2024-25', max_length=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academic.curso')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_generados', to=settings.AUTH_USER_MODEL)),
                ('titulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academic.titulacion')),
            ],
            options={
                'verbose_name': 'Horario Generado',
                'verbose_name_plural': 'Horarios Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='SesionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('aula', models.CharField(blank=True, max_length=20)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='academic.asignatura')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='academic.bloquehorario')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='scheduler.horariogenerado')),
            ],
            options={
                'verbose_name': 'Sesión de Horario',
                'verbose_name_plural': 'Sesiones de Horario',
                'ordering': ['dia', 'bloque__hora_inicio'],
                'unique_together': {('horario', 'dia', 'bloque')},
            },
        ),
    ]
